image: 'maven:alpine'

before_script:
  - apk update && apk add openssl ca-certificates git

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - target/*.war
    expire_in: 1 week

test:
  stage: test
  script:
    - mvn test

deploy:
  stage: deploy
  script:
    - echo "Run dep script here"
    - git clone "$CI_REPOSITORY_URL" icing-mediascanner-java-vfs-native
    - cd icing-mediascanner-java-vfs-native
    - git config user.email "kg6zvp@gmail.com"
    - git config --global user.name "Sam McCollum"
    - git remote add github "https://kg6zvp:$GITHUB_PERSONAL_ACCESS_TOKEN@github.com/kg6zvp/icing-mediascanner-java-vfs-native.git"
    - git push --force --follow-tags github master
    - cd ..
    - rm -rf icing-mediascanner-java-vfs-native
  only:
    - master

after_script:
  - echo "End CI"
